name: test
on:
  push:
    branches: main
    paths-ignore:
      - '**/*.md'
    tags-ignore:
      - '*'
  pull_request:
    branches: main
    paths-ignore:
      - '**/*.md'
jobs:
  test:
    uses: ./.github/workflows/test-jobs.yaml
